name: Inpackages Domain - Pull request

on:
  workflow_dispatch: 
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main

jobs:
  setup:
    uses: setup.yml
    with:
      gitversion: '6.3.0'