name: Inpackages Domain - Pull request

env:
  GITVERSION: 6.3.0

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main
    paths:
      - 'src/Inpackages.Domain/**'

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
    with:
      gitversion: ${{ env.GITVERSION }}